# Generated by Django 6.0.5 on 2026-05-30 06:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PomodoroSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('task_description', models.TextField(blank=True)),
                ('work_duration_minutes', models.PositiveSmallIntegerField(default=25)),
                ('break_duration_minutes', models.PositiveSmallIntegerField(default=5)),
                ('pomodoros_completed', models.PositiveSmallIntegerField(default=0)),
                ('pomodoros_planned', models.PositiveSmallIntegerField(default=4)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('total_focus_minutes', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pomodoro_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'productivity_pomodoro_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FocusLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('focus_minutes', models.PositiveSmallIntegerField(default=0)),
                ('productivity_score', models.FloatField(default=0)),
                ('subjects_studied', models.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_logs', to=settings.AUTH_USER_MODEL)),
                ('pomodoro_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='focus_logs', to='productivity.pomodorosession')),
            ],
            options={
                'db_table': 'productivity_focus_logs',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StudyStreak',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_study_date', models.DateField(blank=True, null=True)),
                ('total_study_days', models.PositiveIntegerField(default=0)),
                ('streak_history', models.JSONField(default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='study_streak', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'productivity_study_streaks',
            },
        ),
        migrations.AddIndex(
            model_name='pomodorosession',
            index=models.Index(fields=['user', 'status'], name='productivit_user_id_bb06d3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='focuslog',
            unique_together={('user', 'date')},
        ),
    ]
