# Generated by Django 6.0.5 on 2026-06-01 13:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('file', models.FileField(upload_to='pdfs/%Y/%m/')),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('page_count', models.PositiveSmallIntegerField(default=0)),
                ('is_processed', models.BooleanField(default=False)),
                ('extracted_text', models.TextField(blank=True)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('tags', models.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pdfs_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PDFChatMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_chat_messages', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='pdfs.pdfdocument')),
            ],
            options={
                'db_table': 'pdfs_chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PDFHighlight',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('page_number', models.PositiveSmallIntegerField(default=1)),
                ('color', models.CharField(default='yellow', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='pdfs.pdfdocument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_highlights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pdfs_highlights',
                'ordering': ['page_number', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pdfdocument',
            index=models.Index(fields=['user', 'subject'], name='pdfs_docume_user_id_bbdef7_idx'),
        ),
        migrations.AddIndex(
            model_name='pdfdocument',
            index=models.Index(fields=['user', 'is_processed'], name='pdfs_docume_user_id_a8596d_idx'),
        ),
    ]
