kind = "api"
previewPath = "/api"
title = "BrainPilot AI - API Server"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8000
name = "API Server"
paths = ["/api"]

[services.development]
run = "pnpm --filter @workspace/api-server run dev"

[services.production]

[services.production.health.startup]
path = "/api/v1/healthz"
