# Generated by Django 6.0.5 on 2026-05-30 06:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('tags', models.JSONField(default=list)),
                ('is_pinned', models.BooleanField(default=False)),
                ('ai_summary', models.TextField(blank=True)),
                ('summary_generated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notes_notes',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('times_reviewed', models.PositiveSmallIntegerField(default=0)),
                ('times_correct', models.PositiveSmallIntegerField(default=0)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('next_review_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='notes.note')),
            ],
            options={
                'db_table': 'notes_flashcards',
                'ordering': ['next_review_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', 'subject'], name='notes_notes_user_id_5fc3af_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', 'is_pinned'], name='notes_notes_user_id_abfd1e_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['user', 'subject', 'next_review_at'], name='notes_flash_user_id_250c65_idx'),
        ),
    ]
