# Generated by Django 6.0.5 on 2026-05-30 06:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisionTopic',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('topic', models.CharField(max_length=255)),
                ('confidence_level', models.IntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Very High')], default=3)),
                ('revision_count', models.PositiveSmallIntegerField(default=0)),
                ('last_revised_at', models.DateTimeField(blank=True, null=True)),
                ('next_revision_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_weak', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_topics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'revision_topics',
                'ordering': ['next_revision_at'],
            },
        ),
        migrations.CreateModel(
            name='RevisionSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duration_minutes', models.PositiveSmallIntegerField()),
                ('confidence_before', models.IntegerField()),
                ('confidence_after', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_sessions', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='revision.revisiontopic')),
            ],
            options={
                'db_table': 'revision_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='revisiontopic',
            index=models.Index(fields=['user', 'is_weak'], name='revision_to_user_id_e254bb_idx'),
        ),
        migrations.AddIndex(
            model_name='revisiontopic',
            index=models.Index(fields=['user', 'subject'], name='revision_to_user_id_036d03_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='revisiontopic',
            unique_together={('user', 'subject', 'topic')},
        ),
    ]
