# Generated by Django 6.0.5 on 2026-05-30 06:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('plan_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('emergency', 'Emergency Exam Mode'), ('custom', 'Custom')], default='daily', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused')], default='draft', max_length=20)),
                ('subjects', models.JSONField(default=list)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_hours', models.PositiveSmallIntegerField(default=0)),
                ('ai_generated', models.BooleanField(default=False)),
                ('ai_context', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'planner_study_plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('topic', models.CharField(max_length=255)),
                ('scheduled_date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_minutes', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=20)),
                ('completion_percentage', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('rescheduled_to', models.DateField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='planner.studyplan')),
            ],
            options={
                'db_table': 'planner_study_sessions',
                'ordering': ['scheduled_date', 'start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='studyplan',
            index=models.Index(fields=['user', 'status'], name='planner_stu_user_id_a34ce3_idx'),
        ),
        migrations.AddIndex(
            model_name='studyplan',
            index=models.Index(fields=['user', 'start_date'], name='planner_stu_user_id_470785_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['plan', 'scheduled_date'], name='planner_stu_plan_id_57a3c6_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['plan', 'status'], name='planner_stu_plan_id_914ed7_idx'),
        ),
    ]
